version: "3"
services:
  fluentd:
    container_name: 'fluentd'
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    depends_on:
      - elasticsearch
    ports:
      - "24224:24224"
      - "24224:24224/udp"
  
  elasticsearch:
    container_name: 'elasticsearch'
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    environment:
      - "discovery.type=single-node"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    expose:
      - "9200"
    ports:
      - "9200:9200"

  kibana:
    container_name: 'kibana'
    image: docker.elastic.co/kibana/kibana:7.13.1
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
  
  nodejs-web-app:
    container_name: 'nodejs-web-app'
    build:
      context: nodejs-web-app
    ports:
      - 8080:8080
    environment: 
      PORT: 8080
    expose:
      - 8080
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: application.nodejs-web-app